### ISSUE TITLE
如何在研究项目中引用？

### ISSUE THREAD

**Issue by TylunasLi** [shijiebei2009/CEEC-Corpus#1]
如何在研究项目中引用您的数据集。是否有指定引用的文献？

**Comment by shijiebei2009** [comment]
直接标注语料库地址吧

中文
环境突发事件语料库，https://github.com/daselab/CEEC-Corpus，2015, 上海大学
英文
CEEC Corpus, https://github.com/daselab/CEEC-Corpus，2015, Shanghai University

**Comment by shijiebei2009** [comment]
@TylunasLi 还可以参考这个文献的引用方式：https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2017&filename=MESS201702012&v=d19hcCSPCC5%25mmd2FmPm55TmMQffALXXIZsxc8pGFYeGl4YXm25U6ulrrBMkj9HI2HgJi
